[package]
name = "orbem"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
bevy = "0.16.0"
bevy_framepace = "0.19.1"
noisy_bevy = "0.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
